name: Deploy test-deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            cd /www/wwwroot/projects/
            ls -al
            rm -rf test-deploy
            git clone git@github.com:HappyPhilosopher/test-deploy.git -b ${{ github.ref_name }}
            cd test-deploy
            npm install
            npm run build