name: Deploy test-deploy
on: [push]
jobs:
  Deploy:
    - uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PWD }}